/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MerkleAirdropMinter } from "./MerkleAirdropMinter";
export type { MyMintableToken } from "./MyMintableToken";
